version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
